import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/app/headercomponents/Header";

const montserrat = Montserrat({
  subsets: ["latin"],
});


export const metadata = {
  title: "Aesthetic | Template",
  description: "Generated by create aesthetic app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}  antialiased`}>
       <Header />
        {children}
      </body>
    </html>
  );
}
