import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/app/headercomponents/Header";
import FooterTop from "./headercomponents/FooterTop";
import FooterBottom from "./headercomponents/FooterBottom";
import { Suspense } from 'react'
import Loading from "./loading";

const montserrat = Montserrat({
  subsets: ["latin"],
});


export const metadata = {
  title: "Aesthetic | Template",
  description: "Generated by create aesthetic app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}  antialiased`}>
        <Suspense fallback={<Loading />}>
       <Header />
        {children}
        <FooterTop />
        <FooterBottom />
        </Suspense>
      </body>
    </html>
  );
}
